In [1]:
import cv2 as cv #import openCv
cv.__version__

'4.10.0'

In [5]:
def showcase(text, img):
    if img is not None:  # Check if the image was loaded properly
        cv.imshow(text, img)   # Show loaded image
        cv.waitKey(0)          # Wait for the key to close 
        cv.destroyAllWindows()  # Destroy image window
    else:
        print("Error: Image not loaded!")

imge = cv.imread("D:\\Viit\\bootcamp\Day_4\\download.jpeg")  # Load image using cv2 as a numpy array
print(imge)  # Check if the image is loaded
showcase("image", imge)

[[[ 67 108  81]
  [ 68 109  82]
  [ 68 109  82]
  ...
  [ 55  94  73]
  [ 55  94  73]
  [ 55  94  73]]

 [[ 68 109  82]
  [ 68 109  82]
  [ 69 110  83]
  ...
  [ 55  94  73]
  [ 55  94  73]
  [ 55  94  73]]

 [[ 68 109  82]
  [ 68 109  82]
  [ 69 110  83]
  ...
  [ 55  94  73]
  [ 55  94  73]
  [ 55  94  73]]

 ...

 [[ 63  97  87]
  [ 61  95  85]
  [ 59  94  84]
  ...
  [ 53  96  99]
  [ 50  93  96]
  [ 46  89  92]]

 [[ 64  98  88]
  [ 61  95  85]
  [ 58  93  83]
  ...
  [ 51  93  98]
  [ 51  93  98]
  [ 50  92  97]]

 [[ 64  98  88]
  [ 62  96  86]
  [ 58  93  83]
  ...
  [ 50  92  97]
  [ 52  94  99]
  [ 53  95 100]]]


In [7]:
imge.shape

(148, 182, 3)

In [8]:
# Basic image oprations using opencv
resize=cv.resize(imge,(500,500))
showcase("resize image",resize)

In [9]:
#convert image into grayscale 
gray_image=cv.cvtColor(resize,cv.COLOR_BGR2GRAY)
showcase("gray images",gray_image)

In [10]:
#Crop image 
crop_img=resize[100:400,100:300]
showcase("crop image",crop_img)

In [11]:
#rotate image
(h,w)=resize.shape[:2]
center=(w//2,h//2)
M=cv.getRotationMatrix2D(center,37,1.0)
rotated=cv.warpAffine(resize,M,(w,h))
showcase("Ratated image",rotated)

In [12]:
#rotate image using rotate function 
showcase("Rotated image using function",cv.rotate(resize,cv.ROTATE_90_CLOCKWISE))


In [13]:
#bluring technique-Gaussin Blurring
blurred_img=cv.GaussianBlur(resize,(5,5),0)
showcase("Gausin Blurred image",blurred_img)


In [14]:
#bluring technique-median blurring
medians=cv.medianBlur(resize,5)
showcase("medain blur",medians)

In [15]:
#bluring technique-bilateral blurring 
bila=cv.bilateralFilter(resize,9,75,75)
showcase("bilateral image",bila)

In [16]:
# bluring technique-average blurring
avg=cv.blur(resize,(5,5))
showcase("Average Bluring",avg)

In [17]:
#image thresholding technique-Binary thresold
_,thresh_img=cv.threshold(gray_image,127,255,cv.THRESH_BINARY)
showcase("Binary tech",thresh_img)

In [19]:
#image thresholding technique-Binary thresold Inverse
_,thresh_img=cv.threshold(gray_image,127,255,cv.THRESH_BINARY_INV)
showcase(" Binary Inverse Threshold tech",thresh_img)

In [20]:
#image thresholding technique-Truncate thresold
_,thresh_img=cv.threshold(gray_image,127,255,cv.THRESH_TRUNC)
showcase(" Truncate  Threshold tech",thresh_img)

In [21]:
#image thresholding technique-Zero thresold
_,thresh_img=cv.threshold(gray_image,127,255,cv.THRESH_TOZERO)
showcase(" Zero Threshold tech",thresh_img)

In [22]:
#image thresholding technique-Zero thresold Inverse
_,thresh_img=cv.threshold(gray_image,127,255,cv.THRESH_TOZERO_INV)
showcase(" Inverse  Zero Threshold tech",thresh_img)

In [23]:
#image thresholding technique-Zero thresold Inverse
_,thresh_img=cv.threshold(gray_image,127,255,cv.THRESH_TOZERO_INV)
showcase("Inverse Threshold tech",thresh_img)

In [24]:
#image thresholding technique-Adpative threshold
thresh_img=cv.adaptiveThreshold(gray_image,255,cv.ADAPTIVE_THRESH_GAUSSIAN_C,cv.THRESH_BINARY,11,2)
showcase("adaptive hreshold tech",thresh_img)

In [31]:
#edge detection
edges=cv.Canny(resize,200,0)
showcase("Canne edge",edges)